### ISSUE TITLE
推荐beetlsql,百度一下

### ISSUE THREAD

**Issue by fxk2006** [blinkfox/zealot#1]

**Comment by blinkfox** [comment]
知道的哈，Java里面国内外的ORM啊、DAO框架啊工具很多我都看过使用过，我这个工具的创造意图是使SQL和SQL参数的动态拼接更简单，目的针对的是动态、纯粹的SQL本身。只要有了易于书写和维护的SQL，就可以在任何框架、工具甚至原生JDBC里面去执行得到结果就行了。设计目的不是DAO工具、ORM之类的吧。
也许以后会演变成ORM之类的吧，但不是zealot，而是HighTemplar！
