### ISSUE TITLE
怎么写 NOT IN ?

### ISSUE THREAD

**Issue by bhsdy** [blinkfox/zealot#2]

**Comment by blinkfox** [comment]
@bhsdy  不好意思，才看到你的问题。

1. 如果你是使用XML标签语法的话，`NOT IN`并没有内置进去，但Zealot是支持自定义扩展的，这可以参考`com.blinkfox.zealot.core.concrete.InHandler.java`中的写法，在自己系统中写一个NotInHandler处理器，然后在你的`ZealotConfig.java`配置类的`configTagHandler`方法中，配置刚才定义的处理器的标签及额外前缀，类似如下的配置：

```java
/**
  * zealot的自定义标签及其处理器配置.
  */
@Override
public void configTagHandler() {
    // 使用自己定义的'Not In'标签的Handler，额外再定义三个标签即可：notIn、andNotIn、orNotIn.
    add("notIn", NotInHandler.class);
    add("andNotIn", " AND NOT ", NotInHandler.class);
    add("orNotIn", " OR NOT ", NotInHandler.class);
}
```

2. 在xml中还有种办法，就是使用更加灵活的流程控制标签，即`@if`、`@foreach`用法，可以完成更多自定义逻辑的控制。

3. 如果你使用的是Java方式的`ZealotKhala.java`的话，可以使用`doAnything`方法来完成你任意的逻辑。

由于自己对`Not In`使用的偏少，所以当时没有添加，感谢你的Issue，后续版本我会增加这些功能。
